language: bash
services: docker

env:
  - VERSION=7.1 VARIANT=
  - VERSION=7.1 VARIANT=alpine
  - VERSION=7.1 VARIANT=apache
  - VERSION=7.1 VARIANT=fpm
  - VERSION=7.0 VARIANT=
  - VERSION=7.0 VARIANT=alpine
  - VERSION=7.0 VARIANT=apache
  - VERSION=7.0 VARIANT=fpm
  - VERSION=5.6 VARIANT=
  - VERSION=5.6 VARIANT=alpine
  - VERSION=5.6 VARIANT=apache
  - VERSION=5.6 VARIANT=fpm
  - VERSION=5.5 VARIANT=
  - VERSION=5.5 VARIANT=alpine
  - VERSION=5.5 VARIANT=apache
  - VERSION=5.5 VARIANT=fpm

before_script:
  - cd "$VERSION"
  - IMAGE="mileschou/phalcon:${VERSION}-${VARIANT:+-$VARIANT}"
  - IMAGE="${IMAGE//'/'/-}"

script:
  - docker build -t "$IMAGE" "${VARIANT:-.}"

after_script:
  - docker images